version: '3'
services:
  systempusDB:
    image: postgres
    restart: unless-stopped
    container_name: systempusDB
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 8001:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8008:8080

